### ISSUE TITLE
Issues with next ggplot2 release

### ISSUE THREAD

**Issue by thomasp85** [Redcart/helda#9]
We have detected issues with helda when checking the next release of ggplot2, due in two weeks

# helda

<details>

* Version: 1.1.1
* Source code: https://github.com/cran/helda
* URL: https://www.github.com/Redcart/helda
* BugReports: https://github.com/Redcart/helda/issues
* Date/Publication: 2020-05-14 11:40:03 UTC
* Number of recursive dependencies: 102

Run `cloud_details(, "helda")` for more info

</details>

## Newly broken

*   checking tests ... ERROR
    ```
      Running ‘testthat.R’
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      Component "layers": Component 3: Component 3: Component 2: target, current do not match when deparsed
      Component "plot_env": Component "plot_2": Component "layers": Component 3: Component 3: Component 2: target, current do not match when deparsed
      
      ── 2. Failure: lift effect for titanic data set (@test-lift_effect.R#18)  ──────
      `result` not equivalent to `lift_effect_test`.
      Component "layers": Component 2: Component 3: Component 2: target, current do not match when deparsed
      Component "plot_env": Component "plot_1": Component "layers": Component 2: Component 3: Component 2: target, current do not match when deparsed
      
      ══ testthat results  ═══════════════════════════════════════════════════════════
      [ OK: 5 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 2 ]
      1. Failure: lift curve for titanic data set (@test-lift_curve.R#18) 
      2. Failure: lift effect for titanic data set (@test-lift_effect.R#18) 
      
      Error: testthat unit tests failed
      Execution halted
    ```

I've looked into your unit test, but since you simply compare two very complex plot objects and see if they are the same it is hard to figure out where the issue lies. Note that we may from time to time change some internals of ggplot2 which will be reflected in the resulting plot object, so comparing the plot object wholesale to a cached one will always be very fragile and hard to maintain. I'd suggest you instead compare specific values you know are important and related to your package code.

We will submit ggplot2 in two weeks so I hope you'll have time to fix the unit test by then. Please reach out if you have any further questions

**Comment by Redcart** [comment]
Thank you for your response. Indeed I am a quite new to R package maintainer. I now see clearly your point about testing the whole object especially with ggplot2 or even dplyr. You are right my goal was not really to test the whole but to make sure that the core of it does not change. I will change the test to focus on specific values as you advice.

Thank you very much for your advices.
